apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mycnpg
spec:
  instances: 3
  storage:
    size: 1Gi
  backup:
    barmanObjectStore:
      endpointURL: "https://fradozn9lozb.compat.objectstorage.eu-frankfurt-1.oraclecloud.com"
      destinationPath: s3://bucket-20240602-2126/part4-cnpg
      serverName: mycpng
      s3Credentials:
        accessKeyId:
          key: accessKeyId
          name: oci-s3-credentials
        secretAccessKey:
          key: secretAccessKey
          name: oci-s3-credentials