apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pg-fixer
  name: pg-fixer
  namespace: cnpg-cluster
spec:
  containers:
  - command:
    - /bin/bash
    - -c
    - sleep 2d
    image: ubuntu
    name: pg-fixer
    resources: {}
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: pgdata
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: pgdata
    persistentVolumeClaim:
      claimName: mycnpg-2 # FIXME: possibly different PVC
status: {}
